server:
  port: 8888

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=UTF8&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

logging:
  level:
    root: debug

# 表配置
config:
  designated: ['tb1','tb2'] # 数据表集合
  designatedPrefix: ["kd"]      # 数据表前缀
  designatedSuffix: []      # 数据表后缀
  ignorePrefix: []          # 忽略表前缀
  ignoreTable: []           # 忽略表
  ignoreSuffix: []          # 忽略后缀
  version: 1.0              # 版本
  description:  数据库科设计文档
  filePath: result
#  文件格式 MD|WORD|HTML
  fileType: WORD


#=======================================配置信息============================================
###mysql
#MYSQL_HOST: 127.0.0.1
#MYSQL_PASSWORD: root
#MYSQL_PORT: 3306
#MYSQL_USERNAME: root
#MYSQL_DATABASE: partner
